openapi: 3.0.1
info:
  title: product-service
  description: Documentation for product-service API
  version: '0.1'
servers:
  - url: 'https://wdzdjsytsh.execute-api.eu-west-1.amazonaws.com'
paths:
  /dev/products:
    get:
      description: Get array of all products
      responses:
        '200':
          description: Successful response with the array of all products, each product corresponds to the product schema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
              examples:
                '0':
                  value: >-
                    [{"id":"909af13e-cfa5-4025-9daf-402697dd7bb9","count":1,"description":"Myrtaceae","price":83,"title":"Oryx gazella callotis","image":"https://images.unsplash.com/photo-1572096440536-480da44a35de?w=400"},{"id":"d6b48bac-b750-4e78-8cda-cba576627cdc","count":2,"description":"Boraginaceae","price":68,"title":"Canis aureus","image":"https://images.unsplash.com/photo-1551044531-ab2753e871c3?w=400"},{"id":"d9a3b1c6-df01-42cc-9bb7-02be9b2c6be5","count":3,"description":"Dryopteridaceae","price":16,"title":"Mephitis mephitis","image":"https://images.unsplash.com/photo-1585992776250-1c0ceb34827f?w=400"},{"id":"ea8ce80c-c03a-432a-8e27-ced7d1a5af7d","count":4,"description":"Boraginaceae","price":2,"title":"Spheniscus magellanicus","image":"https://images.unsplash.com/photo-1601285135794-62115fa4ecf5?w=400"},{"id":"805a4e44-127a-47c8-9850-ffb58d38a082","count":5,"description":"Asteraceae","price":30,"title":"Phoca vitulina","image":"https://images.unsplash.com/photo-1571203962034-6bcf84f23a2b?w=400"},{"id":"edd8b41d-71b4-4503-b32a-900b8306c265","count":6,"description":"Asteraceae","price":52,"title":"Mabuya spilogaster","image":"https://images.unsplash.com/photo-1582238918897-3dd40caf24e3?w=400"},{"id":"fe444562-3737-4fd6-8c5a-213ad85a1f4b","count":7,"description":"Pannariaceae","price":95,"title":"Pseudocheirus peregrinus","image":"https://images.unsplash.com/photo-1579685818514-43fdab45dbd9?w=400"},{"id":"45472c5e-f05b-4563-9d45-f3f8a2a3db32","count":9,"description":"Rosaceae","price":35,"title":"Gyps bengalensis","image":"https://images.unsplash.com/photo-1498121694787-97844766694e?w=400"},{"id":"db080c67-2fd3-4b85-8076-c109049732ad","count":10,"description":"Solanaceae","price":89,"title":"Gymnorhina tibicen","image":"https://images.unsplash.com/photo-1542820243-6c18415893ce?w=400"}]
      servers:
        - url: 'https://wdzdjsytsh.execute-api.eu-west-1.amazonaws.com/'
    servers:
      - url: 'https://wdzdjsytsh.execute-api.eu-west-1.amazonaws.com'
    post:
      requestBody:
        description: example of body, image is optional
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                price:
                  type: number
                count:
                  type: number
                image:
                  type: string
                  format: url
              required:
                - title
                - description
                - price
                - count
            example:
              title: new product 100500
              description: new description 100500
              price: 100
              count: 1
      responses:
        '200':
          description: New product has been created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
              example:
                id: 909af13e-cfa5-4025-9daf-402697dd7aa2
                title: new product
                description: new description
                price: 100
                count: 1
                image: https://images.unsplash.com/photo-1551970634-747846a548cb?w=400
        '400':
          description: Bad request (missing some field or has incorrect field type)
          content:
            application/json:
              schema:
                type: string
              example:
                Bad request
  /dev/products/{productId}:
    get:
      description: Auto generated using Swagger Inspector
      parameters:
        - in: path
          name: productId
          schema:
            type: string
          required: true
          description: id of a product to get
      responses:
        '200':
          description: Successful response with the requested product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
              examples:
                '0':
                  value: >-
                    {"id":"909af13e-cfa5-4025-9daf-402697dd7bb9","count":1,"description":"Myrtaceae","price":83,"title":"Oryx gazella callotis","image":"https://images.unsplash.com/photo-1572096440536-480da44a35de?w=400"}
        '404':
          description: Product with such id was not found
          content:
            application/json:
              schema:
                type: string
              examples:
                '0':
                  value: >-
                    'Product not found'
      servers:
        - url: 'https://wdzdjsytsh.execute-api.eu-west-1.amazonaws.com'
    servers:
      - url: 'https://wdzdjsytsh.execute-api.eu-west-1.amazonaws.com'
components:
  schemas:
    product:
      type: object
      properties:
        id:
          type: string
        count:
          type: number
        description:
          type: string
        price:
          type: number
        title:
          type: string
        image:
          type: string
          format: url
      description: "product schema"