service:
  name: authorization-service

frameworkVersion: '2'

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  profile: personal

  environment:
    olenastarchak: ${env:olenastarchak}

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer

resources:
  Outputs:
    basicAuthorizerArn:
      Value:
        Fn::GetAtt: [ BasicAuthorizerLambdaFunction, Arn]
      Export:
        Name: basicAuthorizerArn